<?php
/**
 * @file
 * tips_tricks.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function tips_tricks_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-tips_tricks-body'.
  $field_instances['node-tips_tricks-body'] = array(
    'bundle' => 'tips_tricks',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Put your super cool tip here.  Be sure and include a brief summary to attract people\'s attention!',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => 1,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-tips_tricks-field_image'.
  $field_instances['node-tips_tricks-field_image'] = array(
    'bundle' => 'tips_tricks',
    'deleted' => 0,
    'description' => 'If you have a picture that helps illustrate this particular tip, upload it here.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_image',
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '640x480',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'large',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-tips_tricks-field_tags'.
  $field_instances['node-tips_tricks-field_tags'] = array(
    'bundle' => 'tips_tricks',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Include some tags to help people find your useful tips!',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_tags',
    'label' => 'Tags',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');
  t('If you have a picture that helps illustrate this particular tip, upload it here.');
  t('Image');
  t('Include some tags to help people find your useful tips!');
  t('Put your super cool tip here.  Be sure and include a brief summary to attract people\'s attention!');
  t('Tags');

  return $field_instances;
}
