<?php

function jj_custom_follow_networks_alter(&$networks, $uid = 0) {
    // Add a network
    $networks[$uid]['imdb'] = array(
        'title' => t('IMDB'),
        'domain' => 'imdb.com',
    );

    $networks[$uid]['drupal'] = array(
        'title' => t('Drupal.org'),
        'domain' => 'drupal.org',
    );

    $networks[$uid]['redbubble'] = array(
        'title' => t('Redbubble'),
        'domain' => 'redbubble.com',
    );

    $networks[$uid]['etsy'] = array(
        'title' => t('Etsy'),
        'domain' => 'etsy.com',
    );

    $networks[$uid]['github'] = array(
        'title' => t('GitHub'),
        'domain' => 'github.com',
    );

    drupal_add_css(drupal_get_path('module', 'jj_custom') . '/css/custom.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}
